### PR TITLE
Fix java compatibility issues

### LINKED ISSUE #31: Java compatibility
- [ ] `KSolver.assert` is not availiable in Java because `assert` is a keyword. 
- [ ] Methods with default arguments  (e.g. `KSolver.check`) are not availiable in Java.

### PR DESCRIPTION
**Pull request by Saloed**
Fix #31

### CODE REVIEW

File: ksmt-core/src/main/kotlin/org/ksmt/solver/KSolver.kt [hunk 1]
```diff
@@ -57,6 +63,8 @@ interface KSolver : AutoCloseable {
      * @see check
      * @see unsatCore
      * */
+    @Suppress("INAPPLICABLE_JVM_NAME")
```
Comment (CaelmBleidd) [inline ksmt-core/src/main/kotlin/org/ksmt/solver/KSolver.kt:66]: Is it correct? Shouldn't it be something like "JvmOverload" instead? I just don't get why is it inapplicable and how this jvmName will help with default arguments

Comment (Saloed) [reply ksmt-core/src/main/kotlin/org/ksmt/solver/KSolver.kt:66]: `JvmName` is not supported for interfaces: https://youtrack.jetbrains.com/issue/KT-31420. 

The Kotlin compiler applies mangling to functions with default arguments in some cases. JvmName allows us to disable mangling and therefore makes the functions accessible from Java.

Comment (Saloed) [reply ksmt-core/src/main/kotlin/org/ksmt/solver/KSolver.kt:66]: It would be nice to use JvmOverload, but it is also unsupported for interfaces and unlike JvmName it can't be suppressed: https://youtrack.jetbrains.com/issue/KT-36102

**Review by CaelmBleidd — APPROVED** [review]
